import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    home: 'Home',
    about: 'About',
    aboutUs: 'About us',
    ourStory: 'Our story',
    ourBeliefs: 'Our beliefs',
    aboutUsContent: 'Learn more about our church family, leadership, and how we serve our community.',
    ourStoryContent: 'Discover the history and journey of our church and how we came to be.',
    ourBeliefsContent: 'We hold to the core beliefs of the Christian faith. Here you can read our statement of faith.',
    ministries: 'Ministries',
    events: 'Events',
    sermons: 'Sermons',
    groups: 'Groups',
    contact: 'Contact',
    give: 'Give',
    login: 'Login',
    logout: 'Logout',
    churchName: 'Graceland Bible Church',
    welcome: 'Welcome to',
    welcomeUser: 'Welcome',
    welcomeSubtext: 'Join us in worship and fellowship!',
    upcomingEvents: 'Upcoming Events',
    latestSermons: 'Latest Sermons',
    ourMinistries: 'Our Ministries',
    viewAll: 'View All',
    register: 'Register',
    watchNow: 'Watch Now',
    sermonsPageTitle: 'Graceland Church Sermons',
    noSermonsYet: 'No Sermon posted yet...',
    noSermonsMatchSearch: 'No sermons match your search.',
    search: 'Search',
    searchPlaceholder: 'Search sermons...',
    learnMore: 'Learn More',
    serviceTimes: 'Service Times',
    sundayMorning: 'Sunday Worship Service',
    sundayEvening: 'Wednesday Young Adults Service',
    wednesdayPrayer: 'Friday Evening Prayer',
    getInTouch: 'Get In Touch',
    address: 'Address',
    phoneNumber: 'Phone',
    emailAddress: 'Email',
    sendMessage: 'Send Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    noEvents: 'There is no upcoming events right now.',
    location: 'Location',
    noMinistries: 'No ministries available right now.',
    ministriesIntro1: "Depending on people's different stages of life, we have appropriate ministries and fellowships at our church. On top of following ministries, we also have multiple small groups for different geographic locations such as Alameda, Oakland, Walnut Creek, and Concord area. We believe that everyone who attends our church should plug in some kind of small group where we learn to love and serve each other.",
    ministriesIntro2: "We also organize summer and winter camp every year where we go to the nature for a couple of days to worship God, study His word, and have fun with our families and friends.",
    childrenMinistryTitle: "Children's Ministry",
    childrenMinistryPara1: "We want to partner with families in raising up the next generation Christ-seeking and Christ-glorifying children. Our teachers strive to create an environment where your children are heard, safe, loved and encouraged. We study God's word, learn how to pray and worship.",
    childrenMinistryPara2: "There are currently three classes: from age one to two, age two to five, and first to fifth grade.",
    youthMinistryTitle: "Youth Ministry (InterHigh)",
    youthMinistryPara1: "Every Sunday, InterHigh volunteers from Gracepoint Church come to our church to provide a Sunday program for middle school and high school students. The program includes a youth-friendly message, small group discussion, and fun activities or games.",
    youngAdultsMinistryTitle: "Young Adults Ministry",
    youngAdultsMinistryPara1: "Every Sunday after the worship service, our young adults aged between 18 and 30 fellowship with each other to discuss either that day's sermon or our dreams and aspirations. Then we play bascketball in our church backyard or go drink boba.",
    womenMinistryTitle: "Women's Ministry",
    womenMinistryPara1: "We have two different women's groups based on age and they meet after the Sunday worship service to go through a book or just drink a Mongolian milk tea and chat with each other.",
    menMinistryTitle: "Men's Ministry",
    menMinistryPara1: "Our men consist of various age groups and backgrounds but we all share same goal of glorifying Christ in our single or married lives, career, and everything we do. We fellowship after the Sunday service and once a year we do men's retreat.",
    marriageMinistryTitle: "Marriage Ministry",
    marriageMinistryPara1: "We support married couples in building Christ-centered marriages through fellowship, study, and retreats. Couples meet regularly to grow together in faith and strengthen their relationship.",
    quickLinks: 'Quick Links',
    copyright: '© 2024 GBC. All rights reserved.',
    signUp: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginSubtitle: 'Welcome back! Please login to your account.',
    signUpSubtitle: 'Create a new account to get started.',
    fillAllFields: 'Please fill in all fields.',
    usernameTooShort: 'Username must be at least 3 characters long.',
    invalidEmail: 'Please enter a valid email address.',
    passwordTooShort: 'Password must be at least 6 characters long.',
    passwordsDoNotMatch: 'Passwords do not match.',
    loginError: 'Login failed. Please check your credentials.',
    signupError: 'Signup failed. Please try again.',
    loggingIn: 'Logging in...',
    signingUp: 'Signing up...',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    usernamePlaceholder: 'Enter your username',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    confirmPasswordPlaceholder: 'Confirm your password',
  },
  mn: {
    home: 'Нүүр',
    about: 'Бидний тухай',
    aboutUs: 'Бидний тухай',
    ourStory: 'Манай түүх',
    ourBeliefs: 'Манай итгэл',
    aboutUsContent: 'Манай сүмийн гэр бүл, удирдлага, нийгэмд үйлчилж буй талаар дэлгэрэнгүй.',
    ourStoryContent: 'Манай сүмийн түүх, замнал болон хэрхэн үүссэн талаар уншина уу.',
    ourBeliefsContent: 'Бид Христ итгэлийн үндсэн итгэлүүдийг баримталдаг. Энд итгэлийн мэдэгдлээ уншиж болно.',
    ministries: 'Үйлчлэлүүд',
    events: 'Арга хэмжээ',
    sermons: 'Номлол',
    groups: 'Бүлгүүд',
    contact: 'Холбоо барих',
    give: 'Өргөх',
    login: 'Нэвтрэх',
    logout: 'Гарах',
    churchName: 'Ивээлт Нутаг Цуглаан',
    welcome: 'тавтай морилно уу!',
    welcomeUser: 'Тавтай морил',
    welcomeSubtext: 'Бидэнтэй хамт үйлчлэл, нөхөрлөлд оролцоорой!',
    upcomingEvents: 'Удахгүй болох арга хэмжээ',
    latestSermons: 'Сүүлийн номлолууд',
    ourMinistries: 'Манай үйлчлэлүүд',
    viewAll: 'Бүгдийг үзэх',
    register: 'Бүртгүүлэх',
    watchNow: 'Үзэх',
    sermonsPageTitle: 'Ивээлт Нутаг Цуглааны Номлолууд',
    noSermonsYet: 'Одоогоор номлол оруулаагүй байна...',
    noSermonsMatchSearch: 'Таны хайлтад тохирох номлол олдсонгүй.',
    search: 'Хайх',
    searchPlaceholder: 'Номлол хайх...',
    learnMore: 'Дэлгэрэнгүй',
    serviceTimes: 'Үйлчлэлийн цаг',
    sundayMorning: 'Ням гаригийн цуглаан',
    sundayEvening: 'Лхагва гаригийн залуучуудын цуглаан',
    wednesdayPrayer: 'Баасан гаригийн оройн залбирал',
    getInTouch: 'Бидэнтэй холбогдох',
    address: 'Хаяг',
    phoneNumber: 'Утас',
    emailAddress: 'Имэйл',
    sendMessage: 'Мессеж илгээх',
    yourName: 'Таны нэр',
    yourEmail: 'Таны имэйл',
    subject: 'Сэдэв',
    message: 'Мессеж',
    noEvents: 'Одоогоор арга хэмжээ байхгүй байна.',
    location: 'Байршил',
    noMinistries: 'Одоогоор үйлчлэл байхгүй байна.',
    ministriesIntro1: "Манай цуглаан дээр хүмүүсийн амьдралын үе шатаас хамааран тэр бүрд тохирох үйлчлэл, нөхөрлөлүүд байдаг. Үйлчлэлүүдээс гадна Alameda, Oakland, Walnut Creek, Concord зэрэг хотуудад байх жижиг эсийн бүлгүүдэд гишүүд маань хамрагддаг. Эдгээр эсийн бүлгүүдээр дамжуулан цуглааны маань ах, эгч дүүс бие биеэ хайрлаж, үйлчлэхэд суралцдаг гэдэгт бид итгэдэг.",
    ministriesIntro2: "Бид жил бүр зун, өвлийн зуслангийн арга хэмжээ зохион байгуулж, хэдэн өдөр байгальд очиж Бурханыг магтан дуулал, Түүний үгийг судалж, гэр бүл найз нөхөдтэйгөө цагийг өнгөрүүлдэг.",
    childrenMinistryTitle: "Хүүхдийн үйлчлэл",
    childrenMinistryPara1: "Бид цуглааны гэр бүлүүдтэй хамтран дараагийн үеийнхнийг Христийг эрж хайдаг, Түүнийг магтдаг болгон өсгөхийн төлөө ажилладаг. Манай багш нар хүүхэд бүр хайрлагдаж, урам зориг авдаг, үг нь бусдад хүрдэг, аюулгүй орчинг бүрдүүлэхийг зорьдог. Манай хүүхдүүд Бурханы үгийг судалж, яаж залбирч бас магтан дуулахад суралцдаг.",
    childrenMinistryPara2: "Цуглааны хүүхдийн үйлчлэл гурван ангитай: нэгээс хоёр насны, хоёроос таван насны, болон сургуулийн нэгээс тавдугаар ангийн хүүхдүүд гэсэн ангиудтай",
    youthMinistryTitle: "Өсвөр Үеийнхний үйлчлэл (InterHigh)",
    youthMinistryPara1: "Ням бүр Gracepoint сүмийн InterHigh сайн дурын ажилчид манай сүмд ирж дунд болон ахлах ангийн сурагчдад ням гаригийн хөтөлбөр явуулдаг. Уг үйлчлэл маань Англи хэл дээр Библи судалж, бас хөгжөөнт тоглоом тоглон цагийг зугаатай өнгөрүүлэхэд чиглэдэг.",
    youngAdultsMinistryTitle: "Залуучуудын үйлчлэл",
    youngAdultsMinistryPara1: "Манай залуучуудын нөхөрлөлд арван жилээ төгссөн коллейж болон их сургуулийн насныхан хамрагдана. Пүрэв гараг бүрийн 18 цагт хамт цуглаж Библи судлаж, хөгжилдөж нөхөрлөдөг.",
    womenMinistryTitle: "Эмэгтэйчүүдийн үйлчлэл",
    womenMinistryPara1: "Манай сүмийн эмэгтэйчүүдийн бүлгийнхэн Ням гарагийн номлолын дараа хамтдаа цай ууж суунгаа нөхөрлөдөг. Мөн сар бүр нэг удаа хамтдаа нэгнийдээ цуглан Библи суурьтай итгэлийн номноос хуваалцаж, суралцдаг. ",
    menMinistryTitle: "Эрэгтэйчүүдийн үйлчлэл",
    menMinistryPara1: "Манай эрэгтэйчүүд насны зөрүү, гэр бүлийн байдал болон ажил, карьер зэргээс үл шалтгаалан амьдралын бүх л үе шатанд Христийг магтах нэгэн зорилготой. Ням гаригийн цуглаанаас хойш сар бүр хамтдаа цуглан Библи суурьтай эрчүүдийн төлөвшилтийн талаархи номоос хуваалцан, санал солилцож нөхөрлөдөг.",
    marriageMinistryTitle: "Гэрлэлийн үйлчлэл",
    marriageMinistryPara1: "Бид гэрлэсэн хосуудыг Христ төвтэй гэр бүлийг бүтээн байгуулахад нь хичээл сургалтаар, судалгаа болон уулзалт нөхөрлөлөөр дамжуулан дэмжлэг үзүүлдэг. Тиймээс хосууд тогтмол цугларан итгэлдээ хамт өсч, харилцаагаа бэхжүүлдэг.",
    quickLinks: 'Холбоосууд',
    copyright: '© 2024 Ивээлт Нутаг Цуглаан. Бүх эрх хуулиар хамгаалагдсан.',
    signUp: 'Бүртгүүлэх',
    username: 'Хэрэглэгчийн нэр',
    email: 'Имэйл',
    password: 'Нууц үг',
    confirmPassword: 'Нууц үг баталгаажуулах',
    loginSubtitle: 'Тавтай морил! Бүртгэлдээ нэвтрэнэ үү.',
    signUpSubtitle: 'Шинэ бүртгэл үүсгэж эхлээрэй.',
    fillAllFields: 'Бүх талбарыг бөглөнө үү.',
    usernameTooShort: 'Хэрэглэгчийн нэр хамгийн багадаа 3 тэмдэгт байх ёстой.',
    invalidEmail: 'Зөв имэйл хаяг оруулна уу.',
    passwordTooShort: 'Нууц үг хамгийн багадаа 6 тэмдэгт байх ёстой.',
    passwordsDoNotMatch: 'Нууц үг таарахгүй байна.',
    loginError: 'Нэвтрэхэд алдаа гарлаа. Нэвтрэх мэдээллээ шалгана уу.',
    signupError: 'Бүртгүүлэхэд алдаа гарлаа. Дахин оролдоно уу.',
    loggingIn: 'Нэвтэрч байна...',
    signingUp: 'Бүртгүүлж байна...',
    noAccount: 'Бүртгэл байхгүй юу?',
    haveAccount: 'Аль хэдийн бүртгэлтэй юу?',
    usernamePlaceholder: 'Хэрэглэгчийн нэрээ оруулна уу',
    emailPlaceholder: 'Имэйлээ оруулна уу',
    passwordPlaceholder: 'Нууц үгээ оруулна уу',
    confirmPasswordPlaceholder: 'Нууц үгээ баталгаажуулна уу',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'mn' : 'en');
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}