import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    home: 'Home',
    about: 'About',
    ministries: 'Ministries',
    events: 'Events',
    sermons: 'Sermons',
    groups: 'Groups',
    contact: 'Contact',
    give: 'Give',
    login: 'Login',
    logout: 'Logout',
    churchName: 'Graceland Bible Church',
    welcome: 'Welcome to',
    welcomeSubtext: 'Join us in worship and fellowship!',
    upcomingEvents: 'Upcoming Events',
    latestSermons: 'Latest Sermons',
    ourMinistries: 'Our Ministries',
    viewAll: 'View All',
    register: 'Register',
    watchNow: 'Watch Now',
    learnMore: 'Learn More',
    serviceTimes: 'Service Times',
    sundayMorning: 'Sunday Worship Service',
    sundayEvening: 'Wednesday Young Adults Service',
    wednesdayPrayer: 'Friday Evening Prayer',
    getInTouch: 'Get In Touch',
    address: 'Address',
    phoneNumber: 'Phone',
    emailAddress: 'Email',
    sendMessage: 'Send Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    noEvents: 'There is no upcoming events right now.',
    location: 'Location',
    noMinistries: 'No ministries available right now.',
    quickLinks: 'Quick Links',
    copyright: '© 2024 GBC. All rights reserved.',
    signUp: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginSubtitle: 'Welcome back! Please login to your account.',
    signUpSubtitle: 'Create a new account to get started.',
    fillAllFields: 'Please fill in all fields.',
    usernameTooShort: 'Username must be at least 3 characters long.',
    invalidEmail: 'Please enter a valid email address.',
    passwordTooShort: 'Password must be at least 6 characters long.',
    passwordsDoNotMatch: 'Passwords do not match.',
    loginError: 'Login failed. Please check your credentials.',
    signupError: 'Signup failed. Please try again.',
    loggingIn: 'Logging in...',
    signingUp: 'Signing up...',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    usernamePlaceholder: 'Enter your username',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    confirmPasswordPlaceholder: 'Confirm your password',
  },
  mn: {
    home: 'Нүүр',
    about: 'Бидний тухай',
    ministries: 'Үйлчлэлүүд',
    events: 'Арга хэмжээ',
    sermons: 'Номлол',
    groups: 'Бүлгүүд',
    contact: 'Холбоо барих',
    give: 'Өргөх',
    login: 'Нэвтрэх',
    logout: 'Гарах',
    churchName: 'Ивээлт Нутаг Цуглаан',
    welcome: 'тавтай морилно уу!',
    welcomeSubtext: 'Бидэнтэй хамт үйлчлэл, нөхөрлөлд оролцоорой!',
    upcomingEvents: 'Удахгүй болох арга хэмжээ',
    latestSermons: 'Сүүлийн номлолууд',
    ourMinistries: 'Манай үйлчлэлүүд',
    viewAll: 'Бүгдийг үзэх',
    register: 'Бүртгүүлэх',
    watchNow: 'Үзэх',
    learnMore: 'Дэлгэрэнгүй',
    serviceTimes: 'Үйлчлэлийн цаг',
    sundayMorning: 'Ням гаригийн цуглаан',
    sundayEvening: 'Лхагва гаригийн залуучуудын цуглаан',
    wednesdayPrayer: 'Баасан гаригийн оройн залбирал',
    getInTouch: 'Бидэнтэй холбогдох',
    address: 'Хаяг',
    phoneNumber: 'Утас',
    emailAddress: 'Имэйл',
    sendMessage: 'Мессеж илгээх',
    yourName: 'Таны нэр',
    yourEmail: 'Таны имэйл',
    subject: 'Сэдэв',
    message: 'Мессеж',
    noEvents: 'Одоогоор арга хэмжээ байхгүй байна.',
    location: 'Байршил',
    noMinistries: 'Одоогоор үйлчлэл байхгүй байна.',
    quickLinks: 'Холбоосууд',
    copyright: '© 2024 Манай сүм. Бүх эрх хуулиар хамгаалагдсан.',
    signUp: 'Бүртгүүлэх',
    username: 'Хэрэглэгчийн нэр',
    email: 'Имэйл',
    password: 'Нууц үг',
    confirmPassword: 'Нууц үг баталгаажуулах',
    loginSubtitle: 'Тавтай морил! Бүртгэлдээ нэвтрэнэ үү.',
    signUpSubtitle: 'Шинэ бүртгэл үүсгэж эхлээрэй.',
    fillAllFields: 'Бүх талбарыг бөглөнө үү.',
    usernameTooShort: 'Хэрэглэгчийн нэр хамгийн багадаа 3 тэмдэгт байх ёстой.',
    invalidEmail: 'Зөв имэйл хаяг оруулна уу.',
    passwordTooShort: 'Нууц үг хамгийн багадаа 6 тэмдэгт байх ёстой.',
    passwordsDoNotMatch: 'Нууц үг таарахгүй байна.',
    loginError: 'Нэвтрэхэд алдаа гарлаа. Нэвтрэх мэдээллээ шалгана уу.',
    signupError: 'Бүртгүүлэхэд алдаа гарлаа. Дахин оролдоно уу.',
    loggingIn: 'Нэвтэрч байна...',
    signingUp: 'Бүртгүүлж байна...',
    noAccount: 'Бүртгэл байхгүй юу?',
    haveAccount: 'Аль хэдийн бүртгэлтэй юу?',
    usernamePlaceholder: 'Хэрэглэгчийн нэрээ оруулна уу',
    emailPlaceholder: 'Имэйлээ оруулна уу',
    passwordPlaceholder: 'Нууц үгээ оруулна уу',
    confirmPasswordPlaceholder: 'Нууц үгээ баталгаажуулна уу',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'mn' : 'en');
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}