import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    homeSlogan: 'Find grace. Grow in faith. Live with purpose.',
    homeSloganSupport: 'A welcoming Mongolian church community centered on Jesus, Scripture, and life together.',
    planYourVisit: 'Plan Your Visit',
    watchLatestSermon: 'Watch Latest Sermon',
    youAreWelcome: 'You are welcome here',
    joinUsThisWeek: 'Join us this week',
    visitIntro: 'Come as you are. We would love to meet you, worship together, and help you feel at home.',
    firstVisitWelcome: 'Your first visit',
    firstVisitDetails: "Easy parking, children's ministry, and a warm welcome for everyone.",
    sundayWorship: 'Sunday Worship',
    sundayWorshipTime: 'Sundays at 3:30 PM',
    fridayPrayer: 'Friday Evening Prayer',
    fridayPrayerTime: 'Fridays at 7:00 PM',
    ourLocation: 'Our Location',
    growInTheWord: 'Grow in the Word',
    latestMessage: 'Latest message',
    homeContentLoading: 'Loading the latest updates...',
    viewAllSermons: 'All Sermons',
    visitSermonsPage: 'Visit Sermons',
    lifeTogether: 'Life together',
    viewAllEvents: 'View All Events',
    noUpcomingEvents: 'There are no upcoming events right now. Check the full calendar for regular gatherings.',
    sundayInvitationTitle: 'Sunday is always coming',
    sundayInvitationCopy: 'Join us this Sunday at 3:30 PM for worship, community, and an encouraging message.',
    findCommunity: 'Find community',
    ministriesForEverySeason: 'Ministries for every season of life',
    exploreMinistries: 'Explore Ministries',
    weAreHereForYou: 'We are here for you',
    needPrayer: 'How can we pray for you?',
    prayerIntro: 'Whatever you are walking through, you do not have to walk through it alone. Share your request with our church family.',
    sharePrayerRequest: 'Share a Prayer Request',
    generosity: 'Practice generosity',
    onlineGiving: 'Online Giving',
    givingIntro: 'Your generosity helps Graceland Bible Church serve our congregation, our neighbors, and ministries beyond our walls.',
    giveOnline: 'Give Online',
    home: 'Home',
    about: 'About',
    aboutUs: 'About us',
    ourStory: 'Our story',
    ourBeliefs: 'Our beliefs',
    aboutUsContent: 'Learn more about our church family, leadership, and how we serve our community.',
    ourStoryContent: 'Discover the history and journey of our church and how we came to be.',
    ourBeliefsContent: 'We hold to the core beliefs of the Christian faith. Here you can read our statement of faith.',
    beliefsDocumentOrg: 'Graceland Bible Church',
    beliefsDocumentTitle: 'Statement of Faith',
    beliefsDocumentSubtitle: 'Southern Baptist Convention — official doctrinal summary',
    ministries: 'Ministries',
    events: 'Events',
    sermons: 'Sermons',
    groups: 'Groups',
    contact: 'Contact',
    give: 'Give',
    login: 'Login',
    staffLogin: 'Staff Login',
    logout: 'Logout',
    churchName: 'Graceland Bible Church',
    welcome: 'Welcome to',
    welcomeUser: 'Welcome',
    welcomeSubtext: 'Join us in worship and fellowship!',
    upcomingEvents: 'Upcoming Events',
    latestSermons: 'Latest Sermons',
    ourMinistries: 'Our Ministries',
    viewAll: 'View All',
    register: 'Register',
    watchNow: 'Watch Now',
    sermonsPageTitle: 'Graceland Church Sermons',
    noSermonsYet: 'No Sermon posted yet...',
    sermonInvitationTitle: 'A message for your week',
    sermonInvitationCopy: 'Watch messages from Graceland on YouTube or explore our Sermons page.',
    watchOnYouTube: 'Watch on YouTube',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    noSermonsMatchSearch: 'No sermons match your search.',
    search: 'Search',
    searchPlaceholder: 'Search sermons...',
    learnMore: 'Learn More',
    serviceTimes: 'Service Times',
    sundayMorning: 'Sunday Worship Service',
    sundayService: 'Sunday Service',
    holidayNewYearsDay: "New Year's Day",
    holidayMlkDay: 'Martin Luther King Jr. Day',
    holidayPresidentsDay: "Presidents' Day",
    holidayMemorialDay: 'Memorial Day',
    holidayJuneteenth: 'Juneteenth',
    holidayIndependenceDay: 'Independence Day',
    holidayLaborDay: 'Labor Day',
    holidayColumbusDay: 'Columbus Day',
    holidayVeteransDay: 'Veterans Day',
    holidayThanksgiving: 'Thanksgiving Day',
    holidayChristmas: 'Christmas Day',
    sundayEvening: 'Wednesday Young Adults Service',
    wednesdayPrayer: 'Friday Evening Prayer',
    getInTouch: 'Get In Touch',
    address: 'Address',
    phoneNumber: 'Phone',
    emailAddress: 'Email',
    sendMessage: 'Send Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    noEvents: 'There is no upcoming events right now.',
    eventsCalendar: 'Events Calendar',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: 'Today',
    allDay: 'All day',
    addEvent: 'Add Event',
    editEvent: 'Edit Event',
    deleteEvent: 'Delete Event',
    saveEvent: 'Save',
    cancel: 'Cancel',
    eventTitle: 'Title',
    eventDescription: 'Description',
    eventDate: 'Date',
    eventStartTime: 'Start time',
    eventEndTime: 'End time',
    eventLocation: 'Location',
    maxAttendees: 'Max attendees',
    confirmDeleteEvent: 'Delete this event?',
    eventsOnDay: 'Events on this day',
    adminRequired: 'Admin login required to edit events.',
    eventSaveError: 'Could not save event. Please try again.',
    eventDeleteError: 'Could not delete event. Please try again.',
    location: 'Location',
    noMinistries: 'No ministries available right now.',
    ministriesIntro1: "Depending on people's different stages of life, we have appropriate ministries and fellowships at our church. On top of following ministries, we also have multiple small groups for different geographic locations such as Alameda, Oakland, Walnut Creek, and Concord area. We believe that everyone who attends our church should plug in some kind of small group where we learn to love and serve each other.",
    ministriesIntro2: "We also organize summer and winter camp every year where we go to the nature for a couple of days to worship God, study His word, and have fun with our families and friends.",
    childrenMinistryTitle: "Children's Ministry",
    childrenMinistryPara1: "We want to partner with families in raising up the next generation Christ-seeking and Christ-glorifying children. Our teachers strive to create an environment where your children are heard, safe, loved and encouraged. We study God's word, learn how to pray and worship.",
    childrenMinistryPara2: "There are currently three classes: from age one to two, age two to five, and first to fifth grade.",
    youthMinistryTitle: "Youth Ministry (InterHigh)",
    youthMinistryPara1: "Every Sunday, InterHigh volunteers from Gracepoint Church come to our church to provide a Sunday program for middle school and high school students. The program includes a youth-friendly message, small group discussion, and fun activities or games.",
    youngAdultsMinistryTitle: "Young Adults Ministry",
    youngAdultsMinistryPara1: "Every Sunday after the worship service, our young adults aged between 18 and 30 fellowship with each other to discuss either that day's sermon or our dreams and aspirations. Then we play bascketball in our church backyard or go drink boba.",
    womenMinistryTitle: "Women's Ministry",
    womenMinistryPara1: "We have two different women's groups based on age and they meet after the Sunday worship service to go through a book or just drink a Mongolian milk tea and chat with each other.",
    menMinistryTitle: "Men's Ministry",
    menMinistryPara1: "Our men consist of various age groups and backgrounds but we all share same goal of glorifying Christ in our single or married lives, career, and everything we do. We fellowship after the Sunday service and once a year we do men's retreat.",
    ministryContentLoading: 'Loading content…',
    ministryContentEmpty: 'More content coming soon.',
    ministryContentCanvasEmpty: 'No event, nothing is here...',
    ministryContentDropHint: 'Drag and drop files here, or browse to upload',
    ministryContentDropActive: 'Drop files to upload',
    ministryContentBrowseFiles: 'Browse files',
    ministryContentUploading: 'Uploading files…',
    ministryContentUploadError: 'Could not upload file.',
    ministryContentUploadInvalid: 'That file type is not supported.',
    ministryContentEmptyAdmin: 'No content yet. Add text, images, or videos below.',
    ministryContentAddText: 'Add text',
    ministryContentAddImage: 'Add image',
    ministryContentAddVideo: 'Add video',
    ministryContentAddFile: 'Add file / folder',
    ministryContentAddEmbed: 'Add slide / embed',
    ministryContentText: 'Text',
    ministryContentTextPlaceholder: 'Write a paragraph…',
    ministryContentImageUrl: 'Image URL',
    ministryContentImageCaption: 'Caption (optional)',
    ministryContentImageCaptionPlaceholder: 'Describe the image',
    ministryContentImageAlt: 'Ministry image',
    ministryContentVideoUrl: 'Video URL',
    ministryContentVideoPlaceholder: 'YouTube, Facebook, or direct video link',
    ministryContentFileTitle: 'Label',
    ministryContentFileTitlePlaceholder: 'e.g. Men\'s retreat slides',
    ministryContentFileUrl: 'Link URL',
    ministryContentFilePlaceholder: 'File, folder, PDF, or PowerPoint link',
    ministryContentEmbedTitle: 'Title (optional)',
    ministryContentEmbedTitlePlaceholder: 'e.g. Sunday study slides',
    ministryContentEmbedUrl: 'Embed URL',
    ministryContentEmbedPlaceholder: 'Google Slides, Drive folder, PowerPoint, or PDF link',
    ministryContentEmptyPlainAdmin: 'This page is blank. Add text, photos, videos, files, or slides below.',
    ministryContentRemove: 'Remove',
    ministryContentSave: 'Save content',
    ministryContentSaving: 'Saving…',
    ministryContentCancel: 'Cancel',
    ministryContentLoadError: 'Could not load ministry content.',
    ministryContentSaveError: 'Could not save ministry content.',
    marriageMinistryTitle: "Marriage Ministry",
    marriageMinistryPara1: "We support married couples in building Christ-centered marriages through fellowship, study, and retreats. Couples meet regularly to grow together in faith and strengthen their relationship.",
    quickLinks: 'Quick Links',
    copyright: '© 2024 GBC. All rights reserved.',
    signUp: 'Sign Up',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginSubtitle: 'Welcome back! Please login to your account.',
    signUpSubtitle: 'Create a new account to get started.',
    fillAllFields: 'Please fill in all fields.',
    usernameTooShort: 'Username must be at least 3 characters long.',
    invalidEmail: 'Please enter a valid email address.',
    passwordTooShort: 'Password must be at least 6 characters long.',
    passwordsDoNotMatch: 'Passwords do not match.',
    loginError: 'Login failed. Please check your credentials.',
    signupError: 'Signup failed. Please try again.',
    loggingIn: 'Logging in...',
    signingUp: 'Signing up...',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    usernamePlaceholder: 'Enter your username',
    emailPlaceholder: 'Enter your email',
    passwordPlaceholder: 'Enter your password',
    confirmPasswordPlaceholder: 'Confirm your password',
  },
  mn: {
    homeSlogan: 'Нигүүлслийг ол. Итгэлээр өс. Зорилготой амьдар.',
    homeSloganSupport: 'Есүс Христ, Бурханы үг болон хамтын амьдралд төвлөрсөн Монгол чуулганы халуун дулаан гэр бүл.',
    planYourVisit: 'Зочлохоо төлөвлөх',
    watchLatestSermon: 'Сүүлийн номлол үзэх',
    youAreWelcome: 'Тавтай морилно уу',
    joinUsThisWeek: 'Энэ долоо хоногт бидэнтэй нэгдээрэй',
    visitIntro: 'Та яг байгаагаараа ирээрэй. Бид тантай танилцаж, хамтдаа мөргөж, гэртээ байгаа мэт мэдрүүлэхийг хүсэж байна.',
    firstVisitWelcome: 'Таны анхны айлчлал',
    firstVisitDetails: 'Тав тухтай зогсоол, хүүхдийн үйлчлэл, хүн бүрд зориулсан халуун дотно угталт.',
    sundayWorship: 'Ням гарагийн мөргөл',
    sundayWorshipTime: 'Ням гараг бүр 15:30 цагт',
    fridayPrayer: 'Баасан гарагийн залбирал',
    fridayPrayerTime: 'Баасан гараг бүр 19:00 цагт',
    ourLocation: 'Манай хаяг',
    growInTheWord: 'Үгэнд өсөх',
    latestMessage: 'Сүүлийн номлол',
    homeContentLoading: 'Сүүлийн мэдээллийг ачаалж байна...',
    viewAllSermons: 'Бүх номлол',
    visitSermonsPage: 'Номлолын хуудас',
    lifeTogether: 'Хамтын амьдрал',
    viewAllEvents: 'Бүх арга хэмжээ',
    noUpcomingEvents: 'Одоогоор удахгүй болох арга хэмжээ байхгүй байна. Тогтмол цугларалтуудыг хуанлиас харна уу.',
    sundayInvitationTitle: 'Ням гараг үргэлж ирнэ',
    sundayInvitationCopy: 'Энэ Ням гарагийн 15:30 цагт мөргөл, нөхөрлөл, урам өгөх номлолд нэгдээрэй.',
    findCommunity: 'Нөхөрлөлөө олоорой',
    ministriesForEverySeason: 'Амьдралын үе бүрд зориулсан үйлчлэл',
    exploreMinistries: 'Үйлчлэлүүдийг үзэх',
    weAreHereForYou: 'Бид таны төлөө энд байна',
    needPrayer: 'Бид таны төлөө хэрхэн залбирах вэ?',
    prayerIntro: 'Та юуг туулж байгаагаас үл хамааран ганцаараа алхах шаардлагагүй. Залбирлын хүсэлтээ манай чуулганы гэр бүлтэй хуваалцаарай.',
    sharePrayerRequest: 'Залбирлын хүсэлт илгээх',
    generosity: 'Өгөөмөр амьдрал',
    onlineGiving: 'Онлайн өргөл',
    givingIntro: 'Таны өгөөмөр сэтгэл манай чуулган, хөршүүд болон бусад үйлчлэлд хүрч үйлчлэхэд тусалдаг.',
    giveOnline: 'Онлайнаар өргөх',
    home: 'Нүүр',
    about: 'Бидний тухай',
    aboutUs: 'Бидний тухай',
    ourStory: 'Манай түүх',
    ourBeliefs: 'Манай итгэл',
    aboutUsContent: 'Манай сүмийн гэр бүл, удирдлага, нийгэмд үйлчилж буй талаар дэлгэрэнгүй.',
    ourStoryContent: 'Манай сүмийн түүх, замнал болон хэрхэн үүссэн талаар уншина уу.',
    ourBeliefsContent: 'Бид Христ итгэлийн үндсэн итгэлүүдийг баримталдаг. Энд итгэлийн мэдэгдлээ уншиж болно.',
    beliefsDocumentOrg: 'Ивээлт Нутаг Цуглаан',
    beliefsDocumentTitle: 'Итгэлийн мэдэгдэл',
    beliefsDocumentSubtitle: 'Өмнөд Баптист Конвенц — албан ёсны судар бичгийн товчлол',
    ministries: 'Үйлчлэлүүд',
    events: 'Арга хэмжээ',
    sermons: 'Номлол',
    groups: 'Бүлгүүд',
    contact: 'Холбоо барих',
    give: 'Өргөх',
    login: 'Нэвтрэх',
    staffLogin: 'Ажилтны нэвтрэх хэсэг',
    logout: 'Гарах',
    churchName: 'Ивээлт Нутаг Цуглаан',
    welcome: 'тавтай морилно уу!',
    welcomeUser: 'Тавтай морил',
    welcomeSubtext: 'Бидэнтэй хамт үйлчлэл, нөхөрлөлд оролцоорой!',
    upcomingEvents: 'Удахгүй болох арга хэмжээ',
    latestSermons: 'Сүүлийн номлолууд',
    ourMinistries: 'Манай үйлчлэлүүд',
    viewAll: 'Бүгдийг үзэх',
    register: 'Бүртгүүлэх',
    watchNow: 'Үзэх',
    sermonsPageTitle: 'Ивээлт Нутаг Цуглааны Номлолууд',
    noSermonsYet: 'Одоогоор номлол оруулаагүй байна...',
    sermonInvitationTitle: 'Таны энэ долоо хоногийн номлол',
    sermonInvitationCopy: 'Graceland-ийн номлолуудыг YouTube-ээр үзэх эсвэл Номлолын хуудсаар зочлоорой.',
    watchOnYouTube: 'YouTube-ээр үзэх',
    openMenu: 'Цэс нээх',
    closeMenu: 'Цэс хаах',
    noSermonsMatchSearch: 'Таны хайлтад тохирох номлол олдсонгүй.',
    search: 'Хайх',
    searchPlaceholder: 'Номлол хайх...',
    learnMore: 'Дэлгэрэнгүй',
    serviceTimes: 'Үйлчлэлийн цаг',
    sundayMorning: 'Ням гаригийн цуглаан',
    sundayService: 'Ням гаригийн үйлчлэл',
    holidayNewYearsDay: 'Шинэ жилийн баяр',
    holidayMlkDay: 'Мартин Лютер Кингийн өдөр',
    holidayPresidentsDay: 'Ерөнхийлөгчдийн өдөр',
    holidayMemorialDay: 'Дурсгалын өдөр',
    holidayJuneteenth: 'Juneteenth',
    holidayIndependenceDay: 'Тусгаар тогтнолын өдөр',
    holidayLaborDay: 'Хөдөлмөрийн өдөр',
    holidayColumbusDay: 'Кolumbus Day',
    holidayVeteransDay: 'Цэргийн баатрын өдөр',
    holidayThanksgiving: 'Алгасах өдөр',
    holidayChristmas: 'Зул сар',
    sundayEvening: 'Лхагва гаригийн залуучуудын цуглаан',
    wednesdayPrayer: 'Баасан гаригийн оройн залбирал',
    getInTouch: 'Бидэнтэй холбогдох',
    address: 'Хаяг',
    phoneNumber: 'Утас',
    emailAddress: 'Имэйл',
    sendMessage: 'Мессеж илгээх',
    yourName: 'Таны нэр',
    yourEmail: 'Таны имэйл',
    subject: 'Сэдэв',
    message: 'Мессеж',
    noEvents: 'Одоогоор арга хэмжээ байхгүй байна.',
    eventsCalendar: 'Арга хэмжээний календарь',
    previousMonth: 'Өмнөх сар',
    nextMonth: 'Дараагийн сар',
    today: 'Өнөөдөр',
    allDay: 'Бүхэл өдөр',
    addEvent: 'Арга хэмжээ нэмэх',
    editEvent: 'Засах',
    deleteEvent: 'Устгах',
    saveEvent: 'Хадгалах',
    cancel: 'Болих',
    eventTitle: 'Гарчиг',
    eventDescription: 'Тайлбар',
    eventDate: 'Огноо',
    eventStartTime: 'Эхлэх цаг',
    eventEndTime: 'Дуусах цаг',
    eventLocation: 'Байршил',
    maxAttendees: 'Оролцогчийн дээд тоо',
    confirmDeleteEvent: 'Энэ арга хэмжээг устгах уу?',
    eventsOnDay: 'Энэ өдрийн арга хэмжээ',
    adminRequired: 'Засахын тулд админ нэвтрэх шаардлагатай.',
    eventSaveError: 'Хадгалж чадсангүй. Дахин оролдоно уу.',
    eventDeleteError: 'Устгаж чадсангүй. Дахин оролдоно уу.',
    weekdaysFull: [
      'Ням гараг',
      'Даваа гараг',
      'Мягмар гараг',
      'Лхагва гараг',
      'Пүрэв гараг',
      'Баасан гараг',
      'Бямба гараг',
    ],
    location: 'Байршил',
    noMinistries: 'Одоогоор үйлчлэл байхгүй байна.',
    ministriesIntro1: "Манай цуглаан дээр хүмүүсийн амьдралын үе шатаас хамааран тэр бүрд тохирох үйлчлэл, нөхөрлөлүүд явагддаг. Цуглаан дээрхи үйлчлэлүүдээс гадна гишүүд маань Alameda, Oakland, Walnut Creek, Concord зэрэг оршин суудаг хотууддаа байх жижиг эсийн бүлгүүдэд хамрагддаг. Эдгээр эсийн бүлгүүдээр дамжуулан цуглааны маань ах, эгч дүүс бие биеэ хайрлаж, үйлчлэхэд суралцдаг юм.",
    ministriesIntro2: "Бид жил бүр зун, өвлийн кэмпийн арга хэмжээ зохион байгуулж, хэдэн өдөр байгальд гарч Бурханыг магтан дуулан, үгийг судалж, гэр бүл найз нөхөдтэйгөө хамт ивээл ерөөл дүүрэн цагийг өнгөрүүлдэг.",
    childrenMinistryTitle: "Хүүхдийн үйлчлэл",
    childrenMinistryPara1: "Бид цуглааны гэр бүлүүдтэй хамтран дараагийн үеийнхнийг Христийг эрж хайдаг, Түүнийг магтдаг болгон өсгөхийн төлөө ажилладаг. Манай багш нар хүүхэд бүр хайрлагдаж, урам зориг авдаг, үг нь бусдад хүрдэг, аюулгүй орчинг бүрдүүлэхийг зорьдог. Манай хүүхдүүд Бурханы үгийг судалж, яаж залбирч бас магтан дуулахад суралцдаг.",
    childrenMinistryPara2: "Цуглааны хүүхдийн үйлчлэл гурван ангитай: нэгээс хоёр насны, хоёроос таван насны, болон сургуулийн нэгээс тавдугаар ангийн хүүхдүүд гэсэн ангиудтай",
    youthMinistryTitle: "Өсвөр Үеийнхний үйлчлэл (InterHigh)",
    youthMinistryPara1: "Ням бүр Gracepoint сүмийн InterHigh сайн дурын ажилчид манай сүмд ирж дунд болон ахлах ангийн сурагчдад ням гаригийн хөтөлбөр явуулдаг. Уг үйлчлэл маань Англи хэл дээр Библи судалж, бас хөгжөөнт тоглоом тоглон цагийг зугаатай өнгөрүүлэхэд чиглэдэг.",
    youngAdultsMinistryTitle: "Залуучуудын үйлчлэл",
    youngAdultsMinistryPara1: "Манай залуучуудын нөхөрлөлд арван жилээ төгссөн коллейж болон их сургуулийн насныхан хамрагдана. Пүрэв гараг бүрийн 18 цагт хамт цуглаж Библи судлаж, хөгжилдөж нөхөрлөдөг.",
    womenMinistryTitle: "Эмэгтэйчүүдийн үйлчлэл",
    womenMinistryPara1: "Манай сүмийн эмэгтэйчүүдийн бүлгийнхэн Ням гарагийн номлолын дараа хамтдаа цай ууж суунгаа нөхөрлөдөг. Мөн сар бүр нэг удаа хамтдаа нэгнийдээ цуглан Библи суурьтай итгэлийн номноос хуваалцаж, суралцдаг. ",
    menMinistryTitle: "Эрэгтэйчүүдийн үйлчлэл",
    menMinistryPara1: "Манай эрэгтэйчүүд насны зөрүү, гэр бүлийн байдал болон ажил, карьер зэргээс үл шалтгаалан амьдралын бүх л үе шатанд Христийг магтах нэгэн зорилготой. Ням гаригийн цуглаанаас хойш сар бүр хамтдаа цуглан Библи суурьтай эрчүүдийн төлөвшилтийн талаархи номоос хуваалцан, санал солилцож нөхөрлөдөг.",
    ministryContentLoading: 'Агуулга ачааллаж байна…',
    ministryContentEmpty: 'Удахгүй нэмэлт агуулга нэмэгдэнэ.',
    ministryContentCanvasEmpty: 'Юу ч байхгүй байна...',
    ministryContentDropHint: 'Файлуудыг чирж оруулах эсвэл сонгох',
    ministryContentDropActive: 'Файлуудыг энд тавина уу',
    ministryContentBrowseFiles: 'Файл сонгох',
    ministryContentUploading: 'Файл байршуулж байна…',
    ministryContentUploadError: 'Файл байршуулж чадсангүй.',
    ministryContentUploadInvalid: 'Энэ төрлийн файл дэмжигдэхгүй.',
    ministryContentEmptyAdmin: 'Одоогоор агуулга байхгүй. Доор текст, зураг эсвэл видео нэмнэ үү.',
    ministryContentAddText: 'Текст нэмэх',
    ministryContentAddImage: 'Зураг нэмэх',
    ministryContentAddVideo: 'Видео нэмэх',
    ministryContentAddFile: 'Файл / хавтас нэмэх',
    ministryContentAddEmbed: 'Слайд / embed нэмэх',
    ministryContentText: 'Текст',
    ministryContentTextPlaceholder: 'Текст бичнэ үү…',
    ministryContentImageUrl: 'Зургийн холбоос',
    ministryContentImageCaption: 'Тайлбар (заавал биш)',
    ministryContentImageCaptionPlaceholder: 'Зургийг тайлбарлана уу',
    ministryContentImageAlt: 'Үйлчлэлийн зураг',
    ministryContentVideoUrl: 'Видеоны холбоос',
    ministryContentVideoPlaceholder: 'YouTube, Facebook эсвэл шууд видео холбоос',
    ministryContentFileTitle: 'Гарчиг',
    ministryContentFileTitlePlaceholder: 'Жишээ нь: Эрчүүдийн retreat слайд',
    ministryContentFileUrl: 'Холбоос',
    ministryContentFilePlaceholder: 'Файл, хавтас, PDF эсвэл PowerPoint холбоос',
    ministryContentEmbedTitle: 'Гарчиг (заавал биш)',
    ministryContentEmbedTitlePlaceholder: 'Жишээ нь: Ням гаригийн судалгаа',
    ministryContentEmbedUrl: 'Embed холбоос',
    ministryContentEmbedPlaceholder: 'Google Slides, Drive хавтас, PowerPoint эсвэл PDF холбоос',
    ministryContentEmptyPlainAdmin: 'Энэ хуудас хоосон байна. Доор текст, зураг, видео, файл эсвэл слайд нэмнэ үү.',
    ministryContentRemove: 'Устгах',
    ministryContentSave: 'Хадгалах',
    ministryContentSaving: 'Хадгалж байна…',
    ministryContentCancel: 'Цуцлах',
    ministryContentLoadError: 'Үйлчлэлийн агуулгыг ачаалж чадсангүй.',
    ministryContentSaveError: 'Үйлчлэлийн агуулгыг хадгалж чадсангүй.',
    marriageMinistryTitle: "Гэрлэлийн үйлчлэл",
    marriageMinistryPara1: "Бид гэрлэсэн хосуудыг Христ төвтэй гэр бүлийг бүтээн байгуулахад нь хичээл сургалтаар, судалгаа болон уулзалт нөхөрлөлөөр дамжуулан дэмжлэг үзүүлдэг. Тиймээс хосууд тогтмол цугларан итгэлдээ хамт өсч, харилцаагаа бэхжүүлдэг.",
    quickLinks: 'Холбоосууд',
    copyright: '© 2024 Ивээлт Нутаг Цуглаан. Бүх эрх хуулиар хамгаалагдсан.',
    signUp: 'Бүртгүүлэх',
    username: 'Хэрэглэгчийн нэр',
    email: 'Имэйл',
    password: 'Нууц үг',
    confirmPassword: 'Нууц үг баталгаажуулах',
    loginSubtitle: 'Тавтай морил! Бүртгэлдээ нэвтрэнэ үү.',
    signUpSubtitle: 'Шинэ бүртгэл үүсгэж эхлээрэй.',
    fillAllFields: 'Бүх талбарыг бөглөнө үү.',
    usernameTooShort: 'Хэрэглэгчийн нэр хамгийн багадаа 3 тэмдэгт байх ёстой.',
    invalidEmail: 'Зөв имэйл хаяг оруулна уу.',
    passwordTooShort: 'Нууц үг хамгийн багадаа 6 тэмдэгт байх ёстой.',
    passwordsDoNotMatch: 'Нууц үг таарахгүй байна.',
    loginError: 'Нэвтрэхэд алдаа гарлаа. Нэвтрэх мэдээллээ шалгана уу.',
    signupError: 'Бүртгүүлэхэд алдаа гарлаа. Дахин оролдоно уу.',
    loggingIn: 'Нэвтэрч байна...',
    signingUp: 'Бүртгүүлж байна...',
    noAccount: 'Бүртгэл байхгүй юу?',
    haveAccount: 'Аль хэдийн бүртгэлтэй юу?',
    usernamePlaceholder: 'Хэрэглэгчийн нэрээ оруулна уу',
    emailPlaceholder: 'Имэйлээ оруулна уу',
    passwordPlaceholder: 'Нууц үгээ оруулна уу',
    confirmPasswordPlaceholder: 'Нууц үгээ баталгаажуулна уу',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'mn' : 'en');
  };

  const t = (key) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
