"""Add ministries table and its associated tables to database'


Revision ID: e67db893abca
Revises: c41e3481f387
Create Date: 2025-11-13 14:25:49.041764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67db893abca'
down_revision = 'c41e3481f387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ministries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ministry_type', sa.String(length=50), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('meeting_schedule', sa.String(length=255), nullable=True),
    sa.Column('meeting_location', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ministry_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], name=op.f('fk_ministry_leaders_ministry_id_ministries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ministry_leaders_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ministry_id', 'user_id', name='unique_ministry_leader')
    )
    op.create_table('ministry_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ministry_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ministry_id'], ['ministries.id'], name=op.f('fk_ministry_members_ministry_id_ministries')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ministry_members_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ministry_id', 'user_id', name='unique_ministry_member')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ministry_members')
    op.drop_table('ministry_leaders')
    op.drop_table('ministries')
    # ### end Alembic commands ###
